### ISSUE TITLE
[BUG] Messing up with nvim-cmp window

### ISSUE THREAD

**Issue by danymat** [luukvbaal/stabilize.nvim#3]
Hello, when trying to code with your plugin, I often get my screen to mess up because of nvim-cmp window. This results of the position being affected, or worse, the content I was writing being written elsewhere

https://user-images.githubusercontent.com/5306901/137848650-57667859-c226-49b8-a817-00e925a0c306.mov

**Comment by luukvbaal** [comment]
I'm using `nvim-cmp` as well and I'm not seeing this behavior, could you share a minimal config with which this occurs?

**Comment by danymat** [comment]
It's weird because it's not always happening. The bug is consistent for me in a `.lua` file, typing `require` and then completing with LuaSnip + Cmp
My cmp setup is here: https://github.com/danymat/dotfiles/blob/master/nvim/lua/configs/cmp.lua

**Comment by luukvbaal** [comment]
Could you check if 
```diff
 function M.restore_windows()
+       if api.nvim_win_get_config(0) ~= "" then return end
```
fixes it, we don't need to restore window for floating window events as it doesn't mess with the buffer viewports.

**Comment by danymat** [comment]
It seems to resolve the bug with this patch

**Comment by luukvbaal** [comment]
Sorry I gave you (and pushed) the wrong patch, should have been https://github.com/luukvbaal/stabilize.nvim/commit/0e74401c331c3ab8075e9637e90bab82ccb3ac07.

https://github.com/luukvbaal/stabilize.nvim/commit/20beace98ed8547fe060611f80dcbd3f2aa9e85a actually just disabled the `restore_windows()` function altogether 🤭. Could you check if the issue is still resolved?

Edit: it's not getting the window config of the floating windows but of the active window so don't think this check actually works...

**Comment by danymat** [comment]
Hello, I still get the issue, when trying to confirm a luasnip snippet

**Comment by luukvbaal** [comment]
Right, can confirm the issue is more prevalent with snippets thanks. Should help with reproducing although I'm still not sure how to filter out floating window events.

**Comment by luukvbaal** [comment]
@danymat @kalvinpearce With https://github.com/luukvbaal/stabilize.nvim/commit/888381b8ca675d664980e8fb5440367b04da55df, `restore_windows()` is no longer run for floating windows as intended. The cursor should no longer jump when typing with autocompletion plugins, please confirm.

There is still weird behavior with snippets(cmp/luasnip) if you also have `auto_open` in trouble.nvim enabled. This happens because entering the snippet usually triggers diagnostics and `restore_windows()` and the snippet insertion seem to be running asynchronously (I see "zt" from `normal! zt` being entered in the buffer). No fix yet. Ideally, trouble.nvim would not auto_open for snippets. Probably even lower level not trigger diagnostic events for snippets.

Without `trouble.nvim` and `auto_open` snippets seem to work fine though, please confirm if you can.

**Comment by luukvbaal** [comment]
https://github.com/luukvbaal/stabilize.nvim/commit/5abff7c23490c3793d4e0f224bc7a8f4d0a10604 seems to fix the snippet issues as well, please confirm. Turns out select mode was causing the unexpected behavior in combination with the normal command to restore the topline.

**Comment by danymat** [comment]
hello, it seems to work well with latest commits

**Comment by axieax** [comment]
It seems like this issue is back for me at least (no random cursor jumps if cmp is disabled). An additional issue exists with [booperlv/nvim-gomove](https://github.com/booperlv/nvim-gomove/issues/1) as well, regardless of cmp.
