### ISSUE TITLE
Jumbling text in insert mode

### ISSUE THREAD

**Issue by kalvinpearce** [luukvbaal/stabilize.nvim#4]
Firstly, sick plugin, pretty keen to use it!
However I am having an issue where the second key I type in insert mode seems to shift my cursor before it? Not exactly sure how to explain so please see the video 🙏🏻

https://user-images.githubusercontent.com/17244425/137911353-048fae03-3674-4899-9954-b4b446519154.mp4

I wonder if it might be some sort of compatibility issue with coc.nvim perhaps?

Let me know what you think and if you need any more info from me

**Comment by luukvbaal** [comment]
Yep, see https://github.com/luukvbaal/stabilize.nvim/issues/3. The `restore_windows()` function is triggered by hover windows. Still looking into it, not sure how to avoid it currently. Ideally we would listen for `WinResized` instead of `WinNew/Closed` events to restore the cursor position but unfortunately no such event exists.

**Comment by kalvinpearce** [comment]
Ahhh dang I will close this issue and subscribe to that one 🙂
