### ISSUE TITLE
breaks fugitive cc to commit

### ISSUE THREAD

**Issue by khalidchawtany** [luukvbaal/stabilize.nvim#6]
In fugitive pressing cc to commit takes you to the window at the top instead of the gitcommit window.

![2021-11-11 23 34 49](https://user-images.githubusercontent.com/1681606/141365327-5e9df3fb-6dc7-468b-b011-f16021294fe6.gif)

**Comment by luukvbaal** [comment]
Not sure what to do about this. It seems vim-fugitive does some funny buissiness with switching back and forth between its status window and the commit window and utilizes `wincmd p` for that rather than the actual window id.

**Comment by luukvbaal** [comment]
You could use something like this as a workaround:

    autocmd WinNew * lua win=vim.api.nvim_get_current_win() vim.defer_fn(function()vim.api.nvim_set_current_win(win) end, 50)

This will switch back to the newly created window after a delay of 50ms, you can experiment with how low you can go.

Going too low makes fugitive throw errors, really weird architecture that it requires switching to the status buffer for its buffer local variables. And lazy that it uses `wincmd p` to switch back and forth between its windows rather than an absolute window id which would have avoided this issue😋

**Comment by khalidchawtany** [comment]
Thanks it solves the issue for me.

**Comment by smjonas** [comment]
I have the same issue. Note, this is a recent issue, i.e. it does not occur with an older commit of `stabilize.nvim`, e.g. https://github.com/luukvbaal/stabilize.nvim/commit/fe4c0e30a5bffd9385f833edb8d68c01c4b2e547.
Can you please check if there were some changes introduced that caused this issue?

Will do some digging myself. Thanks.

**Edit:** it does not work in the older commit..
**Edit 2:** btw thanks for the workaround, that worked :)
